add rebar to the build

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -13,6 +13,7 @@
 # the License.
 
 cd `dirname $0`
+export CURRENT=`pwd`
 
 get () {
     variable_name=$1
@@ -143,6 +144,21 @@ if test ! -s INSTALL; then
 	echo "Broken INSTALL file."
 	exit 1
 fi
+
+
+# build rebar
+export SUPPORT_DIR=$CURRENT/support
+ESCRIPT=`find_program escript`
+ERLC=`find_program erlc`
+
+cd $SUPPORT_DIR/rebar && ${ESCRIPT} bootstrap 1>/dev/null || true
+
+if test ! -e $SUPPORT_DIR/rebar/rebar; then
+    echo "Error when building rebar"
+    exit 1
+fi
+
+cp $SUPPORT_DIR/rebar/rebar $CURRENT/rebar
 
 cat << EOF
 You have bootstrapped Apache CouchDB, time to relax.
